version: "3.9"

services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: hoteldb
    volumes:
      - mongo_data:/data/db

  hotel-api:
    build: .
    container_name: hotel-api
    restart: always
    deploy:
      replicas: 1
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/hoteldb

volumes:
  mongo_data:
